services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=postgres-pwd
      - POSTGRES_DATABASE=banking-system
    networks:
      - app-network  
  api:
    build: .
    container_name: nest-banking-app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge